name = "ai-forwarder"
compatibility_date = "2025-02-21"
main = "src/index.ts"
assets = { directory = "public", binding = "ASSETS" }

[ai]
binding = "AI"

[vars]
DEFAULT_AI_MODEL = "@cf/meta/llama-3-8b-instruct"

[[kv_namespaces]]
binding = "CACHE"
id = "802cf2efee064993bebc235b53830317"
preview_id = "46191dba66f74ce8939ea4876152aa2d"

# wrangler.toml (wsrangler v3.88.0^)
[observability.logs]
enabled = true

[dev]
host = "dev-worker.metalevel.tech"
